project:
  type: book

book:
  title: "R4DataScience"
  subtitle: "A Course offered by Department of Statistics, University of Calicut"
  author: "Mahesh Divakaran"
  date: "1/14/2026"
  sidebar:
    collapse: true
    style: "docked"
    background: '#8FD9FB'
  chapters:
    - index.qmd
    - Author.qmd
    - chapters/03-introduction.qmd
    - chapters/04-environment.qmd
    - chapters/05-datatypes.qmd
    - chapters/06-datastructures.qmd
    - chapters/07-data-import.qmd
    - chapters/08-tidyverse.qmd
    - chapters/09-dplyr.qmd
    - chapters/10-tidyr.qmd
    - chapters/11a-basicplots.qmd
    - chapters/11b-ggplot2.qmd
    - chapters/12-stringr.qmd
    - chapters/13-data-transformation.qmd
    - chapters/14-dates-times.qmd
    - chapters/15-functional-programming.qmd
    - chapters/15.5-forcats.qmd
    - chapters/16-statistics.qmd
    - chapters/17-probability.qmd
    - chapters/18-inference.qmd
    - chapters/19-regression.qmd
    - chapters/20-timeseries.qmd
    - chapters/21-classification.qmd
    - chapters/22-clustering.qmd
    - chapters/23-knn.qmd
    - chapters/24-dtree.qmd
    - chapters/25-modeleval.qmd
    - summary.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme:
      - flatly
      - brand
      - styles.scss
  pdf:
    pdf:
    documentclass: scrbook
    fontsize: 11pt
    geometry: margin=1in
toc: true
toc-depth: 3
toc-location: right
# This grid section is critical for width control
grid:
  body-width: 1200px
number-sections: true
code-copy: true
code-overflow: wrap
  

editor: visual

